"use client";
import { useMemo, useState } from "react";
import type { Concept, ConceptDomain } from "@/types";

const domains: Array<"전체" | ConceptDomain> = ["전체", "지권", "대기", "해양", "천문", "지질 시대"];
const domainColor: Record<ConceptDomain, string> = { 지권: "text-orange-300 border-orange-400/40", 대기: "text-cyan-300 border-cyan-400/40", 해양: "text-blue-300 border-blue-400/40", 천문: "text-violet-300 border-violet-400/40", "지질 시대": "text-emerald-300 border-emerald-400/40" };

export default function ConceptsClient({ concepts, initialDomain }: { concepts: Concept[]; initialDomain?: ConceptDomain }) {
  const safeDomain = initialDomain && domains.includes(initialDomain) ? initialDomain : "전체";
  const [selectedDomain, setSelectedDomain] = useState<"전체" | ConceptDomain>(safeDomain);
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = useMemo(() => concepts.filter((c) => (selectedDomain === "전체" || c.domain === selectedDomain) && (!query.trim() || [c.title, c.summary, c.explanation, c.tags.join(" ")].join(" ").toLowerCase().includes(query.toLowerCase()))), [selectedDomain, query, concepts]);
  const selected = concepts.find((c) => c.id === selectedId) ?? filtered[0] ?? null;
  const related = selected ? selected.relatedConcepts.map((id) => concepts.find((c) => c.id === id)).filter(Boolean) as Concept[] : [];

  return <main className="max-w-7xl mx-auto p-4 sm:p-8 space-y-5">{/* same UI */}
    <section className="glass-panel p-5 sm:p-6 bg-gradient-to-br from-slate-900/80 via-indigo-950/30 to-cyan-950/20"><h1 className="text-3xl font-bold mb-4">개념 탐색</h1><p className="mb-4 text-sm text-slate-300">필요할 때 빠르게 확인하는 개념 라이브러리</p><div className="flex flex-wrap gap-2 mb-4">{domains.map((d) => <button key={d} onClick={() => setSelectedDomain(d)} className={`px-3 py-1.5 rounded-lg border text-sm ${selectedDomain === d ? "bg-earth/20 border-earth text-earth" : "border-white/15 hover:border-earth/60"}`}>{d}</button>)}</div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="제목·요약·설명·태그 검색" className="w-full rounded-xl bg-slate-900/80 border border-white/15 px-4 py-3" /><p className="text-sm text-slate-400 mt-2">총 {filtered.length}개 개념</p></section>
    <section className="grid lg:grid-cols-[1.2fr_1fr] gap-4"><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{filtered.map((c) => <article key={c.id} onClick={() => setSelectedId(c.id)} className={`glass-panel p-4 cursor-pointer border transition hover:shadow-glow ${selected?.id === c.id ? "border-earth" : "border-white/15"}`}><p className={`text-xs inline-flex px-2 py-0.5 rounded-full border ${domainColor[c.domain]}`}>{c.domain}</p><h3 className="font-semibold mt-2">{c.title}</h3><p className="text-sm text-slate-300 mt-2 leading-relaxed">{c.summary}</p></article>)}</div>{selected && <aside className="glass-panel p-5 border border-white/15 h-fit sticky top-4 space-y-4"><div><p className={`text-xs inline-flex px-2 py-0.5 rounded-full border ${domainColor[selected.domain]}`}>{selected.domain}</p><h2 className="text-2xl font-bold mt-2">{selected.title}</h2></div><div><h3 className="font-semibold text-earth">핵심 요약</h3><p className="text-slate-200 leading-relaxed">{selected.summary}</p></div><div><h3 className="font-semibold text-earth">쉬운 설명</h3><p className="text-slate-200 leading-relaxed">{selected.explanation}</p></div><div><h3 className="font-semibold text-earth">시험 포인트</h3><ul className="list-disc ml-5 text-slate-200 space-y-1">{selected.examPoints.map((p) => <li key={p}>{p}</li>)}</ul></div><div><h3 className="font-semibold text-earth">흔한 오개념</h3><ul className="list-disc ml-5 text-slate-200 space-y-1">{selected.misconceptions.map((m) => <li key={m}>{m}</li>)}</ul></div><div><h3 className="font-semibold text-earth">관련 개념</h3><div className="flex flex-wrap gap-2 mt-2">{related.map((r) => <button key={r.id} onClick={() => setSelectedId(r.id)} className="px-2.5 py-1 rounded-md border border-white/20 hover:border-earth/60 text-sm">{r.title}</button>)}</div></div><div><h3 className="font-semibold text-earth">태그</h3><div className="flex flex-wrap gap-2 mt-2">{selected.tags.map((t) => <span key={t} className="text-xs px-2 py-1 rounded bg-white/10 border border-white/10">#{t}</span>)}</div></div></aside>}</section>
  </main>;
}
